<?php
$title = 'Новая категория';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/category', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('descr'));
echo $this->formRow($form->get('parent'));
echo $this->formSubmit($form->get('submit'));
echo $this->formReset($form->get('reset'));
echo $this->form()->closeTag();
?>
<p>
    <a href="<?= $this->url('admin/category'); ?>">Назад</a>
</p>