<?php
$title = 'Редактироваить категорию';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form  = $this->form;
$form->setAttribute('action',
                    $this->url('admin/category',
                               array('action' => 'edit', 'id'     => $form->get('id')->getValue())));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('descr'));
echo $this->formRow($form->get('parent'));
echo $this->formSubmit($form->get('submit'));
echo $this->formSubmit($form->get('reset'));
echo $this->form()->closeTag();