<?php
$title = 'Категории';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('admin/category', array(
        'action'=>'add'));?>">Добавить категорию</a></p>
<table class="table">
<tr>
    <th>ID</th>
    <th>Название</th>
    <th>Родительская категория</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($categories as $category) : ?>
<tr>
    <td><?= $this->escapeHtml($category->getId()); ?></td>
    <td><?= $this->escapeHtml($category->getName()); ?></td>
    <td><?= $this->escapeHtml($category->getParentName()); ?></td>
    <td>
        <a href="<?php echo $this->url('admin/category',
            array('action'=>'edit', 'id' => $category->getId()));?>">Редактировать</a>
        <a href="<?php echo $this->url('admin/category',
            array('action'=>'delete', 'id' => $category->getId()));?>">Удалить</a>
    </td>
</tr>
<?php endforeach; ?>
</table>