<?php
$title = 'Категории';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('category', array(
        'action'=>'add'));?>">Добавить категорию</a></p>

<table class="table">
<tr>
    <th>ID</th>
    <th>Название</th>
    <th>Родителсякая категория</th>
</tr>
<?php foreach($categories as $category) : ?>
<tr>
    <td><?php echo $this->escapeHtml($category->getTitle());?></td>
    <td><?php echo $this->escapeHtml($category->getArtist());?></td>    <td>
        <a href="<?php echo $this->url('category',
            array('action'=>'edit', 'id' => $category->getId()));?>">Редактировать</a>
        <a href="<?php echo $this->url('category',
            array('action'=>'delete', 'id' => $category->getId()));?>">Удалить</a>
    </td>
</tr>
<?php endforeach; ?>